import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import InfoBar from "../components/info-bar";
import Navigation from "../components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" flex items-center justify-center h-screen">
        <div className=" transition-all overflow-hidden h-full w-full lg:h-[95vh] lg:w-[95vw] shadow-lg flex relative">
          <InfoBar />
          <div className=" flex-grow bg-gray-300">
            <div className="w-full h-16 lg:h-0 bg-white shadow-md transition-all"></div>
          </div>
          <Navigation />
        </div>
      </body>
    </html>
  );
}
