import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import InfoBar from "../components/info-bar";
import Navigation from "../components/navigation";
import Image from "next/image";
import BGImage from "../assets/images/bg.jpg";
import CopyrightBar from "../components/copyright-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" flex items-center justify-center h-screen">
        <div className=" transition-all overflow-hidden h-full w-full lg:h-[95vh] lg:w-[95vw] shadow-lg flex relative">
          <InfoBar />
          <div className=" flex-grow bg-gray-300  overflow-y-auto">
            {/** 移动端顶部栏 */}
            <div className="fixed w-full h-16 lg:h-0 bg-white shadow-md transition-all"></div>
            {/** 背景图 */}
            <div className=" overflow-hidden w-full h-fit absolute top-16 lg:top-0 opacity-[0.04]">
              <Image
                src={BGImage}
                alt="背景图"
                className="w-full h-96 object-cover object-top"
              />
            </div>
            <section className=" transition-all  h-full pt-[6.5rem] lg:pt-10 flex flex-col overflow-y-auto justify-between">
              <section className="px-6">{children}</section>
              <CopyrightBar />
            </section>
          </div>
          <Navigation />
        </div>
      </body>
    </html>
  );
}
