import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import InfoBar from "../components/info-bar";
import Navigation from "../components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" flex items-center justify-center h-screen">
        <div className="h-[95vh] w-[95vw] shadow-lg flex">
          <InfoBar />
          <div className=" flex-grow"></div>
          <Navigation />
        </div>
      </body>
    </html>
  );
}
